on: push
name: test
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.17.0'
    - run: go test ./...
